apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    k8sclustervitals.io/scrape: "true"
spec:
  replicas: 6 # Number of pods
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi" # Minimum memory required
              cpu: "250m" # Minimum CPU required (250 millicores)
            limits:
              memory: "256Mi" # Maximum memory allowed
              cpu: "500m" # Maximum CPU allowed
